# Generated by Django 3.2.12 on 2022-05-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220504_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
